BLENDER28 = blender


export:
	$(BLENDER28) src/meshes/chunky.blend --python ../meshtools/export_mesh_from_blender.py -b -- --object_name="Tread" --outpath="src/meshes/tread_chunky.rs"
	$(BLENDER28) src/meshes/simple_tread.blend --python ../meshtools/export_mesh_from_blender.py -b -- --object_name="Plane" --outpath="src/meshes/tread_simple.rs"
